# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/

buildFuture = true
buildDrafts = true

########################################################################################
title = "AI@UCF"
baseurl = "http://localhost:8234/"
copyright = "{year}"
########################################################################################

########################################################################################
## Advanced options
theme = "academic"
enableGitInfo = true  # Get last modified date for content from Git?

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[outputFormats.VideoBanner]
  name = "VideoBanner"
  mediaType = "text/html"
  isHTML = true
  baseName = "banners/video/index"

[outputFormats.EmailBanner]
  name = "EmailBanner"
  mediaType = "text/html"
  isHTML = true
  baseName = "banners/email/index"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS", ]
  page = [ "HTML", "VideoBanner", "EmailBanner" ]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
